
c1 = Character.create(name: "Korsov Whiteacre")

e1 = Encounter.create(id: 1, chapter: "The Ashen Veil", body: "A soothing song beckons Korsov from the abyss. The shadows obscuring his vision gradually fade away as a sickly light stings his eyes. Something pushes Korsov forward, into a writhing mass of flesh and stone. His vision blurred, Korsov stumbles over debris and sways heavily into his surroundings. There is warmth, but it feels unnatural, as if malignant.")

e2 = Encounter.create(id: 2, chapter: "The Ashen Veil", body: "That song, it urges him to escape. Korsov, numb and irrational, deliberately thrashes at his prison. The masses of flesh and stone gradually give way, but Korsov was inpatient. Korsov reaches upward, a cool air embraces the tips of his fingers. He then senses an orange light emanating above. Transfixed by the glow, he leaps. His strength propels him skyward, a cold light rakes against his flesh. He lands hard into a derelict structure, a tower. It is then he feels a long chain tied to his waist. He severs it and hears it land on the ground below.")

e3 = Encounter.create(id: 3, chapter: "The Ashen Veil", body: "For the first time in decades, Korsov inhales deeply, filling his lungs with an oddly cool dense air, and exhaling it sharply. It takes a minute for him to settle his breathing to a normal effortless rhythm. His senses gradually clear and he finds himself sitting by the shattered window of a hollowed building with steel frames, overlooking hundreds of thousands of gaunt, sickly creatures, all marching towards a thick gray dust storm in the distance. Above, high in the sky, an orange sphere meekly drops its light to the hallowed grounds below.")

e4 = Encounter.create(id: 4, chapter: "The Ashen Veil", body: "Korsov leans against the wall and feels a hard object on the small of his back. He reaches behind and pulls out an ornate knife. Something triggers a memory and he grips the knife handle. He expected something to happen, but the knife would not reveal its secret. Korsov stares at his knife for some time, as if contemplating about his role in this world.")

e5 = Encounter.create(id: 5, chapter: "The Ashen Veil", body: "But I knew you, betrayer, when you realized your world was moving forward without you. When you realized you did not belong and that you would never find your place. You saw it before it all unfolded, but you did nothing. Didn't you want to change your reality? I was trying to help you, to save all of us from this curse.")

j1 = Journal.create(character: c1, encounter: e5, date: "The Awakening", body: "I am ... my name is Korsov. That much I do remember. Just a name without meaning. There is an immense weight pulling on my chest. What is down there? The abyss? A hollow, empty, darkness. I lost something, someone? Why can't I remember? Why am I tormented by this sorrow, when I hold nothing dear? Damn you, you nameless creator, for giving me emotions and suffering before all else.")

e6 = Encounter.create(id: 6, chapter: "The Ashen Veil", body: "Resolveless, the accursed Korsov slowly gets on his feet to survey the scenery below. A writhing sea of dust and humanoid bodies clumsily flows toward a singular direction, treading on broken wood, glass, and stone. The horde of hordes is headed toward a great dark fog in the distance. Remenants of a city stand strong against the tides of flesh, though perhaps in a few hundred years, they too will turn to dust. Korsov spots smoke rising from a brownstone building with an attached tower. Of the few remaining glass windows, an orange light emanates through at the end of the structure.")

e7 = Encounter.create(id: 7, chapter: "The Ashen Veil", body: "After climbing down, Korsov gets a good look at the creatures endlessly spawning from the distance. Many are clothed in worn shirts, jackets, trousers, pants, and shoes. Those whose attire are ragged enough to expose flesh revealed pale leathery skin gripping tightly around bone. Their faces are gaunt, sunken cheeks, receding gumlines, milky eyes, and withering hair. They press on hungrily, as if whatever lies beyond would satiate their needs. They pay no attention to Korsov, nor one another seemingly. Though they appear like corpses, there is no smell of decay. Though they appear to have traveled a great distance, there is no sound of breathing. Had Korsov not been forced to push them aside to reach his destination, he may have thought that they were incredibly detailed apparitions. Korsov reaches the smoking building and enters.")
