
c1 = Character.create(name: "Korsov Whiteacre")

e1 = Encounter.create(id: 1, chapter: "The Ashen Veil", body: "A soothing song beckons Korsov from the abyss. The shadows obscuring his vision gradually fade away as a sickly light stings his eyes. Something pushes Korsov forward, into a writhing mass of flesh and stone. His vision blurred, Korsov stumbles over debris and sways heavily into his surroundings. There is warmth, but it feels unnatural, as if malignant.")

e2 = Encounter.create(id: 2, chapter: "The Ashen Veil", body: "That song, it urges him to escape. Korsov, numb and irrational, deliberately thrashes at his prison. The masses of flesh and stone gradually give way, but Korsov was inpatient. Korsov reaches upward, a cool air embraces the tips of his fingers. He then senses an orange light emanating above. Transfixed by the glow, he leaps. His strength propels him skyward, a cold light rakes against his flesh. He lands hard into a derelict structure, a tower. It is then he feels a long chain tied to his waist. He severs it and hears it fall below.")

e3 = Encounter.create(id: 3, chapter: "The Ashen Veil", body: "For the first time in decades, Korsov inhales deeply, filling his lungs with an oddly cool dense air, and exhaling it sharply. It takes a minute for him to settle his breathing to a normal effortless rhythm. His senses gradually clear and he finds himself sitting by the shattered window of a hollowed building with steel frames, overlooking hundreds of thousands of gaunt, sickly creatures, all marching towards a thick gray dust storm in the distance. Above, high in the sky, an orange sphere meekly drops its light to the hallowed grounds below.
")

e4 = Encounter.create(id: 4, chapter: "The Ashen Veil", body: "Korsov leans against the wall and feels a hard object on the small of his back. He reaches behind and pulls out an ornate knife. Something triggers a memory and he grips the knife handle. He expected something to happen, but the knife would not reveal its secret. Korsov stares at his knife for some time, as if contemplating about his role in this world. Resolveless, he slowly gets on his feet to survey the scenery below.")

j1 = Journal.create(character: c1, encounter: e4, date: "???", body: "I am ... my name is Korsov. I serve the Amaranthine Order. That much I do remember. But I have no memory of my mission or of this ashen world and its orange sky. From what I can gather, this world is dying or perhaps already dead. Maybe I died and this is the afterlife, but I see no God or gods. I guess the scriptures may have been wrong, not that I truly believed them anyway.")
